### ISSUE TITLE
The phase "Binary Images" needs a colon after it

### ISSUE THREAD

**Issue by TroikaTronix** [packagesdev/ips2crash#3]
Thanks for the great tool! But, the app MacSymbolicator (https://github.com/inket/MacSymbolicator) won't symbolicate reports generated with ips2crash because the phrase "Binary Images" should have a colon after it. (Real .crash reports have the colon.)

The fix is simple. Change

[tMutableString appendString:@"Binary Images\n"];

to

[tMutableString appendString:@"Binary Images:\n"];

and MacSymbolicator works properly.

**Comment by packagesdev** [comment]
Fixed.
