### ISSUE TITLE
Error occurred when using output option.

### ISSUE THREAD

**Issue by Zvicii** [packagesdev/ips2crash#6]
```
zouyiqi@ZviciiMBP ~ % ips2crash -o /Users/zouyiqi/Downloads /Users/zouyiqi/Downloads/cross-platform-tester-2022-07-04-095409.ips
An error occurred when reading the file '/Users/zouyiqi/Downloads/cross-platform-tester-2022-07-04-095409.ips'.
```
if i dont use the -o option, it works fine, I can copy what I need from the terminal.
But if I add -o option, it reports error.

**Comment by packagesdev** [comment]
The error message is incorrect. I will improve this.

**Comment by packagesdev** [comment]
The correct error should be reported now. Considering the destination you specified, it could be a FDA issue.

**Comment by Zvicii** [comment]
> The correct error should be reported now. Considering the destination you specified, it could be a FDA issue.

whats an FDA issue？ false destination ？

**Comment by packagesdev** [comment]
Full Disk Access. https://macpaw.com/how-to/full-disk-access-mojave

**Comment by Zvicii** [comment]
> Full Disk Access. https://macpaw.com/how-to/full-disk-access-mojave

thx!
